CI: Add conventional commit checker
UEVE-DLL-2024-2025/DLL pull request #19
Opened 2024-09-20 07:11 UTC by ObstinateM

**Contributor**: Mathis Beauville

**Description:** This pull request adds a new job to the existing GitHub Actions workflow to ensure that all commits follow the "Conventional Commit" format. The commit types are dynamically loaded from a `commit_type.json` file, allowing for easy customization and future scalability.

**Main Changes:**

- Added a new job to the existing GitHub Actions workflow to check commit messages.
- Integrated a custom python script to check commit message.
- [Commit types](https://github.com/commitizen/conventional-commit-types/blob/master/index.json) are loaded from a `commit_type.json` file, making it easier to update and manage allowed types.

**Linked Issue:** #6

**Testing:**

The new job was tested to ensure proper validation of commit messages and correct loading of commit types from commit_type.json.
If a commit doesn't comply with the specified format, the workflow will fail, and an error message will be returned. (see `test/failing` branch)

**Instructions:**

After this PR is merged, contributors must ensure that their commits follow the "Conventional Commit" format, with types as defined in `commit_type.json`. Non-compliant commits will result in PR failure during validation.

2024-09-22 20:31 UTC, SMoraisDev commented
On échangera sur cette PR pendant la prochaine séance, ne touche plus a rien stp :)

2024-10-07 18:08 UTC, SebastienMorais requested changes
Peux-tu utiliser des versions d'action plus récentes ?
Soucis de conflit :)

2024-10-08 09:04 UTC, ObstinateM commented on .github/workflows/ci_cd.yml
> +        uses: actions/setup-python@v4
Les autres actions sont en version 4 😢

2024-10-08 09:05 UTC, SMoraisAnsys commented on .github/workflows/ci_cd.yml
> +        uses: actions/setup-python@v4
On peut discuter de ce point demain si tu veux

2024-10-08 09:08 UTC, ObstinateM commented on .github/workflows/ci_cd.yml
> +        uses: actions/setup-python@v4
Done 🥲

2024-10-09 11:39 UTC, merged